"""Transfer endpoints.

NOTE: no `from __future__ import annotations` here — see the comment in
`routers/auth.py`. It breaks slowapi's decorator and turns the request body
into a query parameter.
"""

from uuid import uuid4

from fastapi import APIRouter, Depends, Header, Path, Request, Response, status
from sqlalchemy.orm import Session as DbSession

from app.core.deps import client_ip, get_current_user
from app.core.limiter import TRANSFER_LIMIT, limiter
from app.database import get_db
from app.models import LedgerEntry, Transaction, User, Wallet
from app.schemas.transfer import PartyOut, TransferOut, TransferRequest
from app.services import statement_service, transfer_service

router = APIRouter(prefix="/api", tags=["transfers"])


def _party(db: DbSession, wallet_id) -> PartyOut | None:
    """Resolve a wallet to its owner, or None for the system mint."""
    if wallet_id is None:
        return None
    row = (
        db.query(User)
        .join(Wallet, Wallet.user_id == User.id)
        .filter(Wallet.id == wallet_id)
        .one_or_none()
    )
    return PartyOut(phone=row.phone, full_name=row.full_name) if row else None


def _to_out(
    db: DbSession, txn: Transaction, viewer_wallet_id, *, replay: bool = False
) -> TransferOut:
    entry = (
        db.query(LedgerEntry)
        .filter(
            LedgerEntry.transaction_id == txn.id,
            LedgerEntry.wallet_id == viewer_wallet_id,
        )
        .one_or_none()
    )
    return TransferOut(
        reference=txn.reference,
        status=txn.status.value if hasattr(txn.status, "value") else str(txn.status),
        type=txn.type.value if hasattr(txn.type, "value") else str(txn.type),
        amount=txn.amount,
        note=txn.note,
        created_at=txn.created_at,
        completed_at=txn.completed_at,
        sender=_party(db, txn.sender_wallet_id),
        recipient=_party(db, txn.receiver_wallet_id),
        balance_after=entry.balance_after if entry else None,
        idempotent_replay=replay,
    )


@router.post(
    "/transfers",
    response_model=TransferOut,
    status_code=status.HTTP_201_CREATED,
    summary="Send money to another user",
)
@limiter.limit(TRANSFER_LIMIT)
def create_transfer(
    body: TransferRequest,
    request: Request,
    response: Response,
    idempotency_key: str | None = Header(
        default=None,
        alias="Idempotency-Key",
        # The column is VARCHAR(64). Without this bound an oversized header
        # reaches PostgreSQL raw and returns a 500 from a money endpoint;
        # with it, FastAPI answers 422 before any work is done.
        max_length=64,
        description=(
            "A unique id for this attempt, generated by the client. Retrying with "
            "the same key returns the original transaction instead of sending twice. "
            "Omit it and one is generated per request — which means a retry WILL "
            "send again, so real clients should always supply it."
        ),
    ),
    db: DbSession = Depends(get_db),
    sender: User = Depends(get_current_user),
) -> TransferOut:
    """Move money from your wallet to another user's.

    The sender is always taken from your access token. There is deliberately no
    field for it in this request, so you cannot spend from an account you do not
    hold a token for.

    Try it twice with the same `Idempotency-Key`: the second call returns the
    same `reference` with `idempotent_replay: true`, and the money moves once.
    """
    key = idempotency_key or f"auto-{uuid4()}"

    txn, replay = transfer_service.send_money(
        db,
        sender=sender,
        recipient_phone=body.recipient_phone,
        amount=body.amount,
        pin=body.pin,
        idempotency_key=key,
        note=body.note,
        ip=client_ip(request),
        user_agent=request.headers.get("user-agent"),
    )
    return _to_out(db, txn, sender.wallet.id, replay=replay)


@router.get(
    "/transfers/{reference}",
    response_model=TransferOut,
    summary="Look up one of your transactions",
)
def get_transfer(
    reference: str = Path(min_length=4, max_length=20, examples=["TXN8H2K4M9P"]),
    db: DbSession = Depends(get_db),
    user: User = Depends(get_current_user),
) -> TransferOut:
    """Only transactions you were a party to. Someone else's reference 404s."""
    txn = statement_service.get_transaction_for_user(
        db, reference=reference, wallet_id=user.wallet.id
    )
    return _to_out(db, txn, user.wallet.id)
