"""Transactions and ledger entries — the core of the system.

A Transaction is one business event. LedgerEntries are the immutable, signed
record of what that event did to each wallet. Two rules hold forever:

    SUM(ledger_entries.amount) = 0                      (globally)
    SUM(ledger_entries.amount) = 0 per transaction_id   (per event)

Entries are append-only, enforced by a database trigger (and, where the
`app_user` role exists, by a REVOKE as well) — not by team convention.
"""

from datetime import datetime
from decimal import Decimal
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.enums import TxnStatus, TxnType, txn_status_pg, txn_type_pg


class Transaction(Base):
    __tablename__ = "transactions"
    __table_args__ = (
        CheckConstraint("amount > 0", name="amount_positive"),
        CheckConstraint(
            "sender_wallet_id IS NULL OR receiver_wallet_id IS NULL "
            "OR sender_wallet_id <> receiver_wallet_id",
            name="no_self_transfer",
        ),
        # THE idempotency mechanism. A partial unique index, so a retry loses
        # the race at the database level rather than in an app-level check
        # with a window between read and write.
        Index(
            "uq_idem",
            "initiated_by",
            "idempotency_key",
            unique=True,
            postgresql_where=text("idempotency_key IS NOT NULL"),
        ),
        Index("idx_txn_created", "created_at"),
    )

    id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    reference: Mapped[str] = mapped_column(String(20), nullable=False, unique=True)
    type: Mapped[TxnType] = mapped_column(txn_type_pg, nullable=False)
    status: Mapped[TxnStatus] = mapped_column(
        txn_status_pg, nullable=False, server_default=text("'PENDING'")
    )
    amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    sender_wallet_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("wallets.id")
    )
    receiver_wallet_id: Mapped[UUID | None] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("wallets.id")
    )

    note: Mapped[str | None] = mapped_column(String(255))
    idempotency_key: Mapped[str | None] = mapped_column(String(64))
    initiated_by: Mapped[UUID | None] = mapped_column(PgUUID(as_uuid=True), ForeignKey("users.id"))
    failure_reason: Mapped[str | None] = mapped_column(String(100))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    entries: Mapped[list["LedgerEntry"]] = relationship(
        back_populates="transaction", order_by="LedgerEntry.id"
    )

    def __repr__(self) -> str:  # pragma: no cover - debug aid
        return f"<Transaction {self.reference} {self.type} {self.amount} {self.status}>"


class LedgerEntry(Base):
    """One signed movement against one wallet. Never updated. Never deleted."""

    __tablename__ = "ledger_entries"
    __table_args__ = (
        CheckConstraint("amount <> 0", name="entry_nonzero"),
        Index("idx_entries_wallet", "wallet_id", text("created_at DESC"), text("id DESC")),
        Index("idx_entries_txn", "transaction_id"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    transaction_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("transactions.id"), nullable=False
    )
    wallet_id: Mapped[UUID] = mapped_column(
        PgUUID(as_uuid=True), ForeignKey("wallets.id"), nullable=False
    )

    # Signed: negative is a debit, positive is a credit. Signing the amount is
    # what turns "audit trail" into a one-query invariant.
    amount: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    # Running balance at the moment this entry was written. Statements render
    # without recomputation, and tampering is detectable by replaying the chain.
    balance_after: Mapped[Decimal] = mapped_column(Numeric(15, 2), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Generated by PostgreSQL, read-only here — a convenience for humans
    # reading the table in psql during the demo.
    direction: Mapped[str] = mapped_column(
        String(6),
        Computed("CASE WHEN amount < 0 THEN 'DEBIT' ELSE 'CREDIT' END", persisted=True),
    )

    transaction: Mapped[Transaction] = relationship(back_populates="entries")

    def __repr__(self) -> str:  # pragma: no cover - debug aid
        return f"<LedgerEntry {self.direction} {self.amount}>"
